= Einmal durch die Transkei
Tina Klein
2018-02-03
:jbake-type: post
:jbake-status: draft
:jbake-tags: blog, asciidoc
:idprefix:

Gewalttour 9 Stunden Fahrt nach East London. Unsere Route führt uns duch die Transkei, die von hoher Kriminalität sein soll.
Wir fühlten uns beide aber sehr sicher! Ich glaube ich werde in Deutschland den Tankwart vermissen,
der für dich gegen ein Trinkgeld tankt, evtl noch die Scheiben wischt. Die Frau die uns bediente freute sich tierisch
über umgerechnet 1,50 euro Trinkgeld.
Unser Weg führt uns durch Umtata oder auch Mthatha, ehemalige Hauptstadt der Transkei. Nicht schön, voller Müll
und große Menschenmassen, ausnahmslos Schwarze.
Gegen 17.00 kommen wir in der John Bailie Guest Lodge in East London an.
Beim Rauchen erzählt mir ein anderer Gast, der aus Johannisburg kommt, wir sollten keine Angst haben, um anzuhalten und
uns nette Fleckchen anzuschauen. Europäer wären bezüglich der Sicherheit oft besorgt, müssten es aber nicht sein.
Das half mir, und ich bedschloss mich in Zukunft freier zu fühlen. Sascha stimmte mir zu.
Wir aßen in einem Restaurant draussen direkt am Meer 2 Mal T-Bonesteak mit Beilagen. 1 Mal 450g und 1 Mal 750 g.
Dazu Sprudel und eine Flasche rotwein. Das ganze kostete gerade mal 30 euro!!!
Danach ab ins Bett nach dem Fernsehen.




