= On the runs...
Tina Klein
2018-02-05
:jbake-type: post
:jbake-status: draft
:jbake-tags: blog, asciidoc
:idprefix:

Ich hatte in der Nacht ebenfalls Durchfall bekommen. Da es mir aber wesentlich besser ging als Sascha,
mache ich mich morgens zu Fuß auf den Weg in den Supermarkt.
Da ich an dem Supermarkt versehentlich vorbei lief war ich hin und zurück 1 1/2 Stunden unterwegs, mit Einkauf
2 Stunden! :-) Ich spravh einen jungen, schwarzen (ein Xhosa) an. Er war sehr freundlich und lachte darüber, dass ich den
Supermarkt verpasst hatte, denn der Pickn Pay erwieß sich als Riesen Mall. er begleitete mich sogar dort hin.
Es gibt dort alles.....na ja fast. Zwieback fand ich nicht, dafür deutsches Pumpernickel.
Als ich zurück war, fiel mir ein, dass ich vergessen hatte in der Pharmacy einzukaufen.
Wenig später ghing ich nochmals los. Die Pharmacy befand sich in der Drogerie. Ich bekam in der Apotheke eine
erstklassige Beratung wie beim Arzt.
Mit 4 verschiedenen Medis bewaffnet machte ich mich zum 2. Mal auf den Heimweg.
Da ich nicht damit gerechne hatte, so lange unterwegs zu sein, hatte ich mich nicht eingecremt.
Jetzt habe ich leicht indianische Hautfarbe. :-)




